version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
      post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name backend --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
