### Doc https://github.com/Huachao/vscode-restclient

# Test route (if server is running well)
GET http://localhost:8080/api/v1

# Auth routes
### register
### login
### reset password
### resend verfication code

# Movie Routes
###  paginated movies
GET http://localhost:8080/api/v1/movies?items_per_page=1&page_number=0 
###  all movies
GET http://localhost:8080/api/v1/movies 
### get one movie
GET http://localhost:8080/api/v1/movies/638fc75a5defce938142af26


