### Doc https://github.com/Huachao/vscode-restclient

# Movie Routes
###  paginated movies
GET http://localhost:8080/api/v1/movies?perPage=1&pageNok=0 
###  all movies
GET http://localhost:8080/api/v1/movies 
### get one movie
GET http://localhost:8080/api/v1/movies/638fc75a5defce938142af26